version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql
    env_file: ./mysql/mysql.env
    ports:
    - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
    